version: "3.9"
services:
  nginx:
    build: ./nginx
    restart: on-failure
    volumes:
      - static_volume:/home/app/swipe/static
      - media_volume:/home/app/swipe/media
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    build: .
    restart: always
    command: sh -c "gunicorn Swipe.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/swipe/static
      - media_volume:/home/app/swipe/media
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:14.6
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  redis:
      image: redis:alpine
      restart: always
      env_file:
        - ./.env

  celery:
      restart: always
      build:
        context: .
      command: celery -A Swipe worker -l info
      depends_on:
        - db
        - web
        - redis
      env_file:
        - ./.env


  celery-beat:
      restart: always
      build:
        context: .
      command: celery -A Swipe worker --beat --scheduler django --loglevel=info
      env_file:
        - ./.env
      depends_on:
        - celery
volumes:
  static_volume:
  media_volume:
  postgres_data: