# Generated by Django 3.2 on 2023-05-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.SmallIntegerField(null=True)),
                ('max_price', models.SmallIntegerField(null=True)),
                ('min_area', models.SmallIntegerField(null=True)),
                ('max_area', models.SmallIntegerField(null=True)),
                ('microdistrict', models.CharField(max_length=50, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('house_status', models.CharField(choices=[('apartments', 'Apartments'), ('houses', 'Houses')], max_length=10, null=True)),
                ('condition', models.CharField(choices=[('Need repair', 'Need Repair'), ('Good', 'Good'), ('Bad', 'Bad')], max_length=11, null=True)),
                ('payment_option', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Cryptocurrency', 'Cryptocurrency')], max_length=15, null=True)),
                ('number_rooms', models.SmallIntegerField(null=True)),
                ('destination', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House')], max_length=9, null=True)),
            ],
        ),
    ]
