# Generated by Django 3.2 on 2023-05-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('foundation_document', models.CharField(choices=[('Own', 'Own')], max_length=3)),
                ('destination', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House')], max_length=9)),
                ('number_rooms', models.SmallIntegerField()),
                ('layout', models.CharField(choices=[('Studio', 'Studio'), ('Micro', 'Micro'), ('Loft', 'Loft'), ('Penthouse', 'Penthouse')], max_length=10)),
                ('condition', models.CharField(choices=[('Need repair', 'Need Repair'), ('Good', 'Good'), ('Bad', 'Bad')], max_length=11)),
                ('area', models.SmallIntegerField()),
                ('kitchen_area', models.SmallIntegerField()),
                ('has_balcony', models.BooleanField()),
                ('heating_type', models.CharField(choices=[('Gas', 'Gas'), ('Electrical', 'Electrical')], max_length=11)),
                ('payment_option', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Cryptocurrency', 'Cryptocurrency')], max_length=15)),
                ('agent_commission', models.IntegerField(choices=[(500, 'Small'), (1500, 'Mid'), (3000, 'Big')])),
                ('communication_method', models.CharField(choices=[('Messages', 'Messages'), ('Phone', 'Phone'), ('Message + phone', 'Message Phone')], max_length=15)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('is_moderate', models.BooleanField(default=False)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('moderate_message', models.CharField(choices=[('Incorrect photo', 'Photo'), ('Incorrect price', 'Price'), ('Incorrect description', 'Description')], max_length=25)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcements/images/')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='announcements.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='announcements.announcement')),
            ],
        ),
    ]
