# Generated by Django 3.2 on 2023-05-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residential_complexes', '0001_initial'),
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='residential_complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='residential_complexes.residentialcomplex'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='residential_complexes.floor'),
        ),
    ]
