# Generated by Django 3.2 on 2023-05-02 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residential_complexes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotions', '0001_initial'),
        ('announcements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='promotion_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.promotiontype'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='residential_complex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='residential_complexes.residentialcomplex'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='riser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='residential_complexes.riser'),
        ),
        migrations.AlterUniqueTogether(
            name='announcement',
            unique_together={('floor', 'riser')},
        ),
    ]
