# Generated by Django 3.2 on 2023-05-02 09:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(upload_to='residential_complexes/advantages/')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_excel', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='residential_complexes/documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='residential_complexes/images/')),
                ('order', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='residential_complexes.block')),
            ],
        ),
        migrations.CreateModel(
            name='Riser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risers', to='residential_complexes.section')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentialComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=95, unique=True)),
                ('contact_first_name', models.CharField(max_length=50)),
                ('contact_last_name', models.CharField(max_length=50)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('contact_email', models.EmailField(max_length=254)),
                ('house_status', models.CharField(choices=[('apartments', 'Apartments'), ('houses', 'Houses')], max_length=10)),
                ('house_type', models.CharField(choices=[('multiFamily', 'Multi-family'), ('townhouse', 'Townhouse'), ('condo', 'Condo'), ('singleFamily', 'Single-family')], max_length=12)),
                ('house_class', models.CharField(choices=[('economy', 'Economy'), ('comfort', 'Comfort'), ('business', 'Business'), ('elite', 'Elite')], max_length=8)),
                ('construction', models.CharField(choices=[('precastFoundations', 'Precast foundations'), ('hybridConcrete', 'Hybrid concrete'), ('flatSlabs', 'Flat slabs')], max_length=18)),
                ('territory', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('closedProtected', 'Closed and protected')], max_length=15)),
                ('distance_to_sea', models.SmallIntegerField()),
                ('communal_payments', models.CharField(choices=[('payments', 'Payments')], max_length=8)),
                ('ceiling_height', models.FloatField()),
                ('gas', models.CharField(choices=[('without', 'Without'), ('central', 'Central')], max_length=8)),
                ('heating', models.CharField(choices=[('without', 'Without'), ('central', 'Central')], max_length=8)),
                ('sewerage', models.CharField(choices=[('without', 'Without'), ('central', 'Central')], max_length=8)),
                ('water_supply', models.CharField(choices=[('without', 'Without'), ('central', 'Central')], max_length=8)),
                ('advantages', models.ManyToManyField(to='residential_complexes.Advantage')),
            ],
        ),
    ]
