# Generated by Django 3.2 on 2023-05-02 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residential_complexes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialcomplex',
            name='builder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='residential_complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='residential_complexes.residentialcomplex'),
        ),
        migrations.AddField(
            model_name='image',
            name='residential_complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='residential_complexes.residentialcomplex'),
        ),
        migrations.AddField(
            model_name='floor',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='residential_complexes.section'),
        ),
        migrations.AddField(
            model_name='document',
            name='residential_complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='residential_complexes.residentialcomplex'),
        ),
        migrations.AddField(
            model_name='block',
            name='residential_complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='residential_complexes.residentialcomplex'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('block', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='riser',
            unique_together={('section', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('residential_complex', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('section', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('residential_complex', 'name')},
        ),
    ]
